global:
   scrape_interval: 20s
   evaluation_interval: 20s


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'ecs_cluster'
    static_configs:
      - targets: ['localhost:9222', 'localhost:9100']
